# Top-level configuration
name = "nft-marketplace"
main = "index.ts"
compatibility_date = "2024-12-20"

[[kv_namespaces]]
binding = "NFT_MARKETPLACE"
id = "a8d87929f21b461a8a822241fd8c2126"

[triggers]
crons = ["0 */12 * * *"]

[observability.logs]
enabled = true